server:
  port: 8081

spring:
  application:
    name: server-provider

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/168404
    username: postgres
    password: 114514
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# 日志编码配置
logging:
  charset:
    console: UTF-8
    file: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
